<html>
<head>
<title>
this is my project
</title>
<link href="add.css" rel="stylesheet" type="text/css">
</head>
<body>
<center>
<p> حذف القاعة  </p>
</center>
<header>
<ul id='right-nav'> 
<li><a href= "pro.php" ><big>الصفحة الرئيسية </big></a></li></ul>
<ul id='right-nav'>  
<li><a href= "delete.php" ><big>الغاء الحجز</big> </a></li>
<li><a href=" add.php"><big>العروض الأضافية</big></a></li>
<li><a href="date of select.php"><big>تاريخ الحجز</big></a></li>
<li><a href="hall.php"><big>القاعات</big></a></li>
</ul></header>
</br> </br></br>

 <form  action="manger delete hall.php" method='post'>
<div class="body">
		    <center>
			 <br>
		   
	        <div class="borderflight">
	            
	            <form>
	               <p style='color:black;font-size:25'>
				   
				أدخل أسم القاعة :
                   <input type="text" name="name" size="40" required></abbr>
				  <br>
				  <br>
				  <center>
	               <button type="submit"  value="حفظ">حذف القاعة </button>
				   </center>
				   </form></p><BR>
			    
	    
		   </div>
<blockquote>
			<blockquote>
			<img src="m/90.jpeg" width="540" height="330">
		    <img src="m/88.jpg" width="540" height="330">
			<br>
	        <img src="m/91.jpg" width="540" height="330">
		    <img src="m/87.jpg" width="540" height="330">
			<br>
			<br>
  
	    </div>
	
    <table align="right" style="background-color:#333333;">
<tbody> <tr valign="top">
<td><table   dir="rtl" width="830" height="800" style="background-color:#f5f5f5;"></td>
</tbody></table>
<td>

<table  dir="rtl" width="1500" padding="20px"margin="20px" >
<tbody>
<tr>
	    <td style="color:white;"><h2 align='right'>معلومات عنا 
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		</h2> </font></td>&nbsp&nbsp&nbsp&nbsp
	    <td style="color:white;"><h2 align='right'>مساعدة 
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		</h2> </font></td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		<td style="color:white;"><h2 align='right'>احجزوا
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		</h2> </font></td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		<td style="color:white;"><h2 align='right'>مزيد من المعلومات
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		</h2> </font></td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		
</tr>
<tr>
	  <td><font color="ffffff"size=4><li>من نحن</li></font>
	  <font color="ffffff"size=4><li>كيف نعمل</li></font>
	  <font color="ffffff"size=4><li>مركز الإعلام</li></font>
	  <font color="ffffff"size=4><li>فريق القيادة</li></font>
	  </td>
	  <td><font color="ffffff"size=4><li>المساعدة والاتصال</li></font>
	  <font color="ffffff"size=4><li>المساعدة الخاصة</li></font>
	  <font color="ffffff"size=4><li>أحدث المعلومات عن الحجوزات</li></font>
	  <font color="ffffff"size=4><li>الأسئلة الشائعة</li></font>
	  </td>
	
	  <td><font color="ffffff"size=4><li>خدمة السيارة مع سائق</li></font>
	  <font color="ffffff"size=4><li>قوموا بإدارة حجزكم</li></font>
	  <font color="ffffff"size=4><li>معلومات عن  اشكال القاعات المتوفره</li></font>
	<font color="ffffff"size=4><li>معلومات الحجز</li></font>
	</td>
	<td><font color="ffffff"size=4><li>مزايا القاعه</li></font>
	<font color="ffffff"size=4><li>تجربة حجزكم </li></font>
	<font color="ffffff"size=4><li>الوجبات</li></font>
		<font color="ffffff"size=4><li>الترفيه في الأجواء</li></font>
	
	 <font color="ffffff" size=4><li>حجز القاعات</li></font>
	  <font color="ffffff"size=4><li>التخطيط لزفافكم</li></font>
		
</td>	  
</br>
</table>
</br>
<hr size="1" color="white" width="100%" >
<table  dir="rtl" width="1500" padding="10px"margin="10px" >
<tbody>


</br>
</table>
<hr size="1" color="white" width="100%" >
<table  dir="rtl" width="1500" padding="10px"margin="10px" >
<tbody>
<tr>
<td><font color="ffffff"size=4>الاشتراك بالعروض الخاصة </font></td>
<td><font color="ffffff"size=4>التطبيقات والموقع على الهاتف</font></td>
<td><font color="ffffff"size=4>تابع اخر التحديثات معنا </font></td>
</tr>
<tr>
<td> <h4><font color="ffffff" size=4> التوفير مع أحدث الأسعار والعروض من قاعات الزفاف</br></font>
<font color="ffffff"size=4>إلغاء الاشتراك أو تغيير خياراتك المفضلة </br></font></td>
<td><font color="ffffff"size=4>حجز القاعه</br> </font></td>
<td><font color="ffffff"size=4>شارك تجربتك مع قاعات الزفاف</h4> </br></font></td>

	  </tr>
</br>
<tr>
<td> <input  id ="subm" type="email"  placeholder="عنوان البريد الألكتروني">
&nbsp&nbsp&nbsp&nbsp
<input  id ="subz" type="submit"  name='submit' value=" أشتراك "size=" 10"  />
</br>
</br>
<font color="ffffff" size=4>لمزيد من التفاصيل عن كيفية استخدامنا لمعلوماتكم، </font>
</br>
<font color="ffffff"size=4>يرجى الاطلاع على سياسة الخصوصية الخاصة بنا. </font>
</td>
<td>  <a href="http://www.apple.com/">
<img src="m/app store.PNG"> &nbsp&nbsp&nbsp&nbsp
<a href="http://play.google.com/">
<img src="m/google.PNG">
</td>
<td> 
       <a href="http://m.facebook.com/">
     <img src="m/f.PNG" width="50" height="25"> &nbsp
	  <a href="http://www.googel.com/">
     <img src="m/g.PNG"width="50" height="25">&nbsp
	  <a href="http://www.instagram.com/">
     <img src="m/in.PNG"width="50" height="25">&nbsp
	  <a href="http://www.youtube.com/">
     <img src="m/y.PNG"width="50" height="25">&nbsp
	  <a href="http://twitter.com/">
	  <img src="m/t.PNG"width="50" height="25">&nbsp
</td>
</tr>
</table>
 <hr size="1" color="white" width="100%" >
<table  dir="rtl" width="1500" padding="5px"margin="5px" >
<tr>
<td><font color="ffffff"size=4>إمكانية الدخول</td>
<td><font color="ffffff"size=4>تواصلوا معنا</td>
<td><font color="ffffff"size=4>سياسة الخصوصية</td>
<td><font color="ffffff"size=4>سياسة ملفات تعريف الارتباط</td>
<td><font color="ffffff"size=4>أمن الإنترنت</td>
<td><font color="ffffff"size=5>خريطة الموقع</td>
</tr>

</table></tbody> 
</br> </br> 


    </body>
	<style type="text/css">
	.borderflight  {
   
    background-color: #DC143C;
	border: 1px solid black;
    height: 350px;
    width: 800px; 
    margin: 50px;
border-radius:20px;
	padding: 30px;
	background-position:center;
}
   input{
 width:400px;
 height:50px;
 background-color:white;
font-size:20px;
color :black;
   }
    button {
 width:200px;
 height:40px;
 background-color:black;
font-size:20px;
color :white;
   }
</style>
</html>